### Criar um novo Lead
POST http://localhost:8082/api/leads
Content-Type: application/json

{
    "empresa": "lexcorp",
    "cnpj": "121451819",
    "valorContrato": 300.00
}

### Listar todos os leads
GET http://localhost:8082/api/leads